site_name: Hanxun Wu
site_url: https://www.hxwu.top

copyright: Copyright &copy; 2025 Hanxun Wu

repo_url: https://github.com/abwuge/personal_website
repo_name: abwuge/personal_website

theme:
  name: material
  custom_dir: overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - header.autohide
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - name: GitHub | abwuge
      icon: fontawesome/brands/github
      link: https://github.com/abwuge
    - name: QQ | AAA太阳能维修
      icon: fontawesome/brands/qq
      link: https://qm.qq.com/q/9K8KOH8IP6 # The link was extracted by decoding a QQ 'Add Friend' QR code.
    - name: WeChat | AAA太阳能维修
      icon: simple/wechat
      link: /wechat/
    - name: Email | abwuge
      icon: fontawesome/solid/envelope
      link: mailto:abwuge@163.com

plugins:
  - search
  - i18n:
      locales:
        - name: 中文
          link: /zh/
          lang: zh
          site_name: 吴函迅食用指南
          nav:
            - 我:
                - me/index.md
                - me/personal_information.md
        - name: English
          link: /en/
          lang: en
          site_name: Hanxun Wu's Website
          nav:
            - Me:
                - me/index.md
                - me/personal_information.md
